 and as the processs goes on .....this is the second file under git commands list
  before continuing for git commmands list .......
  first I want to recall some of linux commands, which may help us in future.
